from pathlib import Path

REQUEST_TIMEOUT = 30
MAX_RETRIES = 2
LISTING_PAGE_SIZE = 500

PROJECT_ROOT_DIR = Path(__file__).resolve().parents[2]
LOG_DIR = PROJECT_ROOT_DIR / "log"

SERVER_ROOT_DIR = Path(r"\\servidor\AUTOMACOES\CONTABILIDADE\FISCAL\IMPORTACAO PARA O QUESTOR")
OUTPUT_SUCCESS_DIR = SERVER_ROOT_DIR / "CONCLUIDO"
OUTPUT_ERROR_DIR = SERVER_ROOT_DIR / "ERRO"